"use client";
import { useEffect, useState } from "react";
import { slugify } from "../../lib/catalog";

export default function Admin(){
 const [logged,setLogged]=useState(false),[password,setPassword]=useState(""),[c,setC]=useState({collections:[],products:[]}),[message,setMessage]=useState(""),[uploading,setUploading]=useState(false);
 const [col,setCol]=useState({name:"",description:"",cover:""}); const [prod,setProd]=useState({name:"",collection:"",category:"Fabrics",description:"",details:"",images:[],featured:false,newArrival:false,available:true});
 useEffect(()=>{fetch("/api/admin/catalog").then(r=>{if(r.ok){setLogged(true);return r.json()} throw 0}).then(setC).catch(()=>{})},[]);
 const login=async()=>{const r=await fetch("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password})});if(r.ok){setLogged(true);setMessage("Welcome to POOJAVI Studio");const d=await fetch("/api/admin/catalog").then(x=>x.json());setC(d)}else setMessage("Invalid password")};
 const save=async(next)=>{const r=await fetch("/api/admin/catalog",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(next)});if(r.ok){setC(next);setMessage("Published successfully.")}else setMessage((await r.json()).error||"Could not save.")};
 const addCol=async(e)=>{e.preventDefault();const item={id:crypto.randomUUID(),slug:slugify(col.name),...col};const next={...c,collections:[...c.collections,item]};await save(next);setCol({name:"",description:"",cover:""})};
 const addProd=async(e)=>{e.preventDefault();const item={id:crypto.randomUUID(),slug:slugify(prod.name),...prod};const next={...c,products:[...c.products,item]};await save(next);setProd({name:"",collection:c.collections[0]?.slug||"",category:"Fabrics",description:"",details:"",images:[],featured:false,newArrival:false,available:true})};
 const upload=async(file,kind)=>{if(!file)return;setUploading(true);const fd=new FormData();fd.append("file",file);const r=await fetch("/api/admin/upload",{method:"POST",body:fd});const d=await r.json();setUploading(false);if(!r.ok){setMessage(d.error);return} if(kind==="cover")setCol(x=>({...x,cover:d.url}));else setProd(x=>({...x,images:[...x.images,d.url]}));};
 if(!logged)return <main className="admin-login"><div className="login-card"><p className="eyebrow">POOJAVI STUDIO</p><h1>Admin access</h1><input type="password" placeholder="Admin password" value={password} onChange={e=>setPassword(e.target.value)}/><button className="button dark" onClick={login}>Enter Studio</button><p>{message}</p></div></main>;
 return <main className="admin"><header className="admin-head"><div><p className="eyebrow">POOJAVI STUDIO</p><h1>Catalogue</h1></div><button onClick={async()=>{await fetch("/api/admin/logout",{method:"POST"});location.reload()}}>Sign out</button></header><p className="status">{message}</p><div className="admin-grid"><section className="admin-card"><h2>New collection</h2><form onSubmit={addCol}><input required placeholder="Collection name" value={col.name} onChange={e=>setCol({...col,name:e.target.value})}/><textarea placeholder="Short description" value={col.description} onChange={e=>setCol({...col,description:e.target.value})}/><input type="file" accept="image/*" onChange={e=>upload(e.target.files?.[0],"cover")}/>{col.cover&&<img className="upload-preview" src={col.cover}/>}<button className="button dark">Publish collection</button></form></section><section className="admin-card"><h2>New product</h2><form onSubmit={addProd}><input required placeholder="Product name" value={prod.name} onChange={e=>setProd({...prod,name:e.target.value})}/><select required value={prod.collection} onChange={e=>setProd({...prod,collection:e.target.value})}><option value="">Choose collection</option>{c.collections.map(x=><option key={x.id} value={x.slug}>{x.name}</option>)}</select><input placeholder="Category" value={prod.category} onChange={e=>setProd({...prod,category:e.target.value})}/><textarea placeholder="Description" value={prod.description} onChange={e=>setProd({...prod,description:e.target.value})}/><textarea placeholder="Details: weave, width, care, etc." value={prod.details} onChange={e=>setProd({...prod,details:e.target.value})}/><input type="file" accept="image/*" multiple onChange={e=>[...e.target.files].forEach(f=>upload(f,"product"))}/>{uploading&&<p>Uploading…</p>}<div className="mini-gallery">{prod.images.map(x=><img key={x} src={x}/>)}</div><label className="check"><input type="checkbox" checked={prod.featured} onChange={e=>setProd({...prod,featured:e.target.checked})}/> Featured</label><label className="check"><input type="checkbox" checked={prod.newArrival} onChange={e=>setProd({...prod,newArrival:e.target.checked})}/> New arrival</label><label className="check"><input type="checkbox" checked={prod.available} onChange={e=>setProd({...prod,available:e.target.checked})}/> Available</label><button className="button dark">Publish product</button></form></section></div><section className="admin-card"><h2>Current collections</h2><div className="admin-list">{c.collections.map(x=><div key={x.id}><strong>{x.name}</strong><span>{c.products.filter(p=>p.collection===x.slug).length} products</span></div>)}</div></section></main>
}
